version: "2"

run:
  concurrency: 4
  timeout: 5m

linters:
  default: standard
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - durationcheck
    - errname
    - errorlint
    - gocheckcompilerdirectives
    - gocritic
    - gosec
    - misspell
    - nilerr
    - predeclared
    - reassign
    - recvcheck
    - revive
    - testifylint
    - thelper
    - unconvert
    - unparam
    - usestdlibvars
  disable:
    - err113
    - exhaustruct
    - gochecknoglobals
    - gochecknoinits
    - godox
    - interfacebloat
    - ireturn
    - lll
    - mnd
    - paralleltest
    - testpackage
    - varnamelen
    - wrapcheck
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: _test\.go
        linters:
          - gosec
          - contextcheck
          - bodyclose

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
