run:
  concurrency: 4
  timeout: 5m

linters:
  presets:
    - bugs
    - error
    - format
    - metalinter
    - performance
    - sql
    - style
    - test
    - unused
    - import
  disable:
    - goerr113
    - interfacebloat
    - exhaustruct
    - wrapcheck
    - varnamelen
    - gci
    - testpackage
    - paralleltest
    - ireturn
    - gochecknoglobals
    - exhaustivestruct
    - lll
    - gochecknoinits
    - ifshort
    - vetshadow
    - maligned
    - interfacer
    - godox
    - scopelint
    - golint
  issues:
    exclude:
      - 'declaration of "(err|ctx)" shadows declaration at'
