// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.12
// source: testserver/testserver.proto

package testserver

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testserver_testserver_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_testserver_testserver_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_testserver_testserver_proto_rawDescGZIP(), []int{0}
}

type NonEmpty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int32 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *NonEmpty) Reset() {
	*x = NonEmpty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testserver_testserver_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NonEmpty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NonEmpty) ProtoMessage() {}

func (x *NonEmpty) ProtoReflect() protoreflect.Message {
	mi := &file_testserver_testserver_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NonEmpty.ProtoReflect.Descriptor instead.
func (*NonEmpty) Descriptor() ([]byte, []int) {
	return file_testserver_testserver_proto_rawDescGZIP(), []int{1}
}

func (x *NonEmpty) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_testserver_testserver_proto protoreflect.FileDescriptor

var file_testserver_testserver_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x74, 0x65, 0x73, 0x74, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x74, 0x65, 0x73,
	0x74, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x74,
	0x65, 0x73, 0x74, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x22, 0x20, 0x0a, 0x08, 0x4e, 0x6f, 0x6e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x32, 0xa1, 0x01, 0x0a, 0x0c, 0x54, 0x65, 0x73, 0x74, 0x73, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2d, 0x0a, 0x02, 0x4f, 0x6b, 0x12, 0x11, 0x2e, 0x74, 0x65,
	0x73, 0x74, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x14,
	0x2e, 0x74, 0x65, 0x73, 0x74, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x4e, 0x6f, 0x6e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x12, 0x2d, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x11, 0x2e,
	0x74, 0x65, 0x73, 0x74, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x1a, 0x11, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x12, 0x33, 0x0a, 0x06, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x11, 0x2e,
	0x74, 0x65, 0x73, 0x74, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x1a, 0x14, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x4e, 0x6f,
	0x6e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x30, 0x01, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x61, 0x68, 0x62, 0x6f, 0x75, 0x62, 0x69, 0x69,
	0x2f, 0x67, 0x72, 0x70, 0x63, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x2f, 0x74, 0x65, 0x73,
	0x74, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_testserver_testserver_proto_rawDescOnce sync.Once
	file_testserver_testserver_proto_rawDescData = file_testserver_testserver_proto_rawDesc
)

func file_testserver_testserver_proto_rawDescGZIP() []byte {
	file_testserver_testserver_proto_rawDescOnce.Do(func() {
		file_testserver_testserver_proto_rawDescData = protoimpl.X.CompressGZIP(file_testserver_testserver_proto_rawDescData)
	})
	return file_testserver_testserver_proto_rawDescData
}

var file_testserver_testserver_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_testserver_testserver_proto_goTypes = []interface{}{
	(*Empty)(nil),    // 0: testserver.Empty
	(*NonEmpty)(nil), // 1: testserver.NonEmpty
}
var file_testserver_testserver_proto_depIdxs = []int32{
	0, // 0: testserver.TestsService.Ok:input_type -> testserver.Empty
	0, // 1: testserver.TestsService.Error:input_type -> testserver.Empty
	0, // 2: testserver.TestsService.Stream:input_type -> testserver.Empty
	1, // 3: testserver.TestsService.Ok:output_type -> testserver.NonEmpty
	0, // 4: testserver.TestsService.Error:output_type -> testserver.Empty
	1, // 5: testserver.TestsService.Stream:output_type -> testserver.NonEmpty
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_testserver_testserver_proto_init() }
func file_testserver_testserver_proto_init() {
	if File_testserver_testserver_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_testserver_testserver_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testserver_testserver_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NonEmpty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_testserver_testserver_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_testserver_testserver_proto_goTypes,
		DependencyIndexes: file_testserver_testserver_proto_depIdxs,
		MessageInfos:      file_testserver_testserver_proto_msgTypes,
	}.Build()
	File_testserver_testserver_proto = out.File
	file_testserver_testserver_proto_rawDesc = nil
	file_testserver_testserver_proto_goTypes = nil
	file_testserver_testserver_proto_depIdxs = nil
}
